[package]
name = "dart_js_lib_gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
swc_common = { version = "0.11.1", features = ["tty-emitter"] }
swc_ecma_ast = "0.49.0"
swc_ecma_parser = "0.64.0"
