[package]
name = "dart_js_lib_gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alloc_counter = "0.0.4"
anyhow = "1.0.45"
ariadne = "0.1.3"
flexi_logger = "0.19.6"
flutter_rust_bridge = "1.6.0"
log = "0.4.14"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
swc_common = { version = "0.11.1", features = ["tty-emitter"] }
swc_ecma_ast = "0.49.0"
swc_ecma_parser = "0.64.0"
