name: dart_js_lib_gen
description: A simple command-line application.
version: 1.0.0
repository: https://github.com/Desdaemon/dart_js_lib_gen

environment:
  sdk: '>=2.14.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  ffi: ^1.1.2
  flutter_rust_bridge: ^1.6.0
  js: ^0.6.3
  path: ^1.8.0
