[package]
name = "dart_js_lib_gen_atoms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
lasso = "0.6.0"
lazy_static = "1.4.0"
