name: Code Coverage
on:
  - push
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Z instrument-coverage"
      LLVM_PROFILE_FILE: "dart_js_lib_gen-%p-%m.profraw"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: Install grcov
        run: |
          curl -L https://github.com/mozilla/grcov/releases/download/v0.8.2/grcov-linux-x86_64.tar.bz2 -o grcov.tar.bz2
          tar -xf grcov.tar.bz2
          chmod +x ./grcov
      - name: Build transformer
        run: cargo +nightly build
      - name: Transform samples
        run: |
          target/debug/dart_js_lib_gen \
            --log error -w \
            --rename-overloads \
            --dynamic-undefs \
            samples/*.ts
      - name: Generate code coverage report
        run: |
          ./grcov . \
            --binary-path target/debug \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            -o lcov.info
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
